# 06 – NumPy

Core operations using NumPy arrays: creation, manipulation, computation, and selection.

---

Part of the [Foundations: Python, R & SQL](../README.md) repository.


## 1. Creating Arrays

Use `np.array`, `np.zeros`, or `np.ones` to create NumPy arrays.

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.zeros((2, 3))
c = np.ones((2, 2))
a, b, c

(array([1, 2, 3]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.]]))

## 2. Indexing and Slicing

In [2]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])
print("Element at row 0, col 1:", x[0, 1])
print("First row:", x[0, :])
x[x < 5] = 0
x

Element at row 0, col 1: 2
First row: [1 2 3]


array([[0, 0, 0],
       [0, 5, 6]])

## 3. Mathematical Operations

In [3]:
x = np.array([1, 2, 3])
np.exp(x), np.sin(x), np.log(x), x + 2, x * 3

(array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([0.84147098, 0.90929743, 0.14112001]),
 array([0.        , 0.69314718, 1.09861229]),
 array([3, 4, 5]),
 array([3, 6, 9]))

## 4. Statistical Methods

In [4]:
x = np.array([4, 7, 2, 9])
x.mean(), x.sum(), x.min(), x.max(), x.std(), x.argmin(), x.argmax()

(5.5, 22, 2, 9, 2.692582403567252, 2, 3)

## 5. Transposing Arrays

In [5]:
mat = np.array([[1, 2], 
                [3, 4]])
mat.T

array([[1, 3],
       [2, 4]])

## 6. Conditional Indexing

In [6]:
x = np.array([[5, 10], 
              [15, 30], 
              [20, 45]])
x[(x[:, 1] > 10) & (x[:, 1] <= 40)]

array([[15, 30]])

## 7. Combining Arrays

In [7]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
np.column_stack((a, b))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

## 8. Computing Business Metrics

In [8]:
unit_price = np.array([10, 15, 20])
quantities = np.array([1, 3, 2])
ca = unit_price * quantities
ca.sum()  # Total revenue

95

## 9. Unique Values

In [9]:
x = np.array([1, 2, 2, 3, 1, 4])
np.unique(x, return_counts=True)

(array([1, 2, 3, 4]), array([2, 2, 1, 1], dtype=int64))

## 10. Applying Promotions

In [10]:
promotions = np.array([0.8, 0.9, 1.0])  # discount factors
new_prices = unit_price * promotions
new_ca = (new_prices * quantities).sum()
new_ca

88.5

## Summary Table

| Functionality             | Syntax / Usage                               | Description                                  |
|---------------------------|-----------------------------------------------|----------------------------------------------|
| Array Creation            | `np.zeros()`, `np.ones()`, `np.array()`       | Create arrays with fixed shape and values    |
| Indexing and Slicing      | `x[i, j]`, `x[start:stop, :]`                 | Access parts of an array                     |
| Mathematical Operations   | `np.exp(x)`              | Element-wise computation                     |
| Statistics                | `mean()`, `sum()`, `std()`, `argmax()`        | Analyze numeric arrays                       |
| Transpose                 | `x.T`                                         | Flip rows and columns                        |
| Conditional Indexing      | `x[x < 0]`, `x[x[:,1] > 10]`                  | Filter elements based on conditions          |
| Combine Arrays            | `np.column_stack((A, B))`                     | Merge arrays column-wise                     |
| Unique Elements           | `np.unique(x, return_counts=True)`            | Count distinct elements                      |