# 02 – Lists, Matrices, and Arrays

Core R concepts: creating and working with compound data structures.

*Part of the [Foundations: Python, R & SQL](../README.md) series.*

## 1. Lists

Lists can contain elements of different types and structures. Useful for grouped results or complex data.

In [1]:
# Create a list
person <- list(name = "Alice", age = 30, scores = c(90, 85, 88))

In [2]:
# Access elements
person$name
person[["scores"]]
person[[3]][2]  # second score

[1] "Alice"

[1] 90 85 88

[1] 85

## 2. Matrices

Matrices are 2D structures with homogeneous data types. Created using the `matrix()` function.

In [3]:
# Create a matrix (fill by column)
m1 <- matrix(1:6, nrow = 2, ncol = 3)
print(m1)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [4]:
# Access elements
print(m1[1, 2])

[1] 3


In [5]:
m1[, 3]  # third column

[1] 5 6

### Matrix operations

In [6]:
# Basic arithmetic
m2 <- matrix(6:1, nrow = 2)
print(m2)

     [,1] [,2] [,3]
[1,]    6    4    2
[2,]    5    3    1


In [7]:
# Operations
m1 + m2
m1 * m2

[,1] [,2] [,3]
[1,] 7    7    7   
[2,] 7    7    7

[,1] [,2] [,3]
[1,]  6   12   10  
[2,] 10   12    6

## 3. Arrays

Arrays extend matrices to more than two dimensions.

In [8]:
# Create a 3D array
a <- array(1:8, dim = c(2, 2, 2))
print(a)

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8



In [9]:
# Accessing elements
a[1, 2, 1]
a[, , 2]  # second layer

[1] 3

[,1] [,2]
[1,] 5    7   
[2,] 6    8

## Summary

| Structure | Type        | Dimensions | Key Feature                     |
|-----------|-------------|------------|----------------------------------|
| List      | Heterogeneous | 1D        | Flexible grouping                |
| Matrix    | Homogeneous   | 2D        | Numeric operations, compact form|
| Array     | Homogeneous   | 3D+       | Multidimensional data support    |